// Generated by CoffeeScript 1.7.1
(function() {
  define(['jquery', 'data'], function($, Data) {
    var CreateElement, createElement, proto;
    CreateElement = function() {};
    proto = CreateElement.prototype;
    proto.create = function(power) {
      var $element, $number, color, number;
      power = power || (Math.random() > 0.2 ? 1 : 2);
      number = Math.pow(2, power);
      color = Data.colors[power - 1];
      $element = $('<div class="element"></div>').data({
        power: power,
        number: number,
        color: color
      }).css({
        width: Data.divWidth,
        height: Data.divWidth,
        background: 'rgba(' + color + ', 0.15)',
        boxShadow: '0 0 12px rgba(' + color + ', 0.5)'
      });
      $number = $('<h1 class="number"></h1>').html(number).css({
        textShadow: '0 0 12px rgba(' + color + ', 0.5)'
      });
      if (number >= 100 && number < 1000) {
        $number.css({
          fontSize: '50px'
        });
      } else if (number >= 1000 && number < 10000) {
        $number.css({
          fontSize: '45px'
        });
      } else if (number >= 10000) {
        $number.css({
          fontSize: '38px'
        });
      }
      $element.append($number);
      return $element[0];
    };
    return createElement = new CreateElement();
  });

}).call(this);

//# sourceMappingURL=element.map
